### PR TITLE
Clean up index

### PR DESCRIPTION
**Pull request by omegahm**
Also rectified a spelling error (`danish` vs. `Danish`)

### CODE REVIEW

**Comment by koppen** [comment]
This seems fairly arbitrary - one sentence per line? What grammatical school dictates that? :confused: 

Is this the result of some linter or what's the deal here?

**Comment by omegahm** [comment]
It is fairly arbitrary, however I have found it easier to read and work with.

No grammatical school, because HTML is like honey badger in this case, it doesn't care. :smirk:

**Comment by koppen** [comment]
So the next pull request is going to be someone who happens to like a different, arbitrary style. How about one paragraph per line, leaving it up to editor settings to appeal to personal preference?

Alternatively, wrap at 80 characters and leave it at that. At least that discussion has been had tons of times ;)

**Comment by jamiehodge** [comment]
I find this easier to read after the changes. Any harm in merging them?

**Comment by koppen** [comment]
I don't find it easier to read, but then again, I am not the one who's going to be managing the site, so my opinion probably shouldn't count for all that much.

**Comment by jamiehodge** [comment]
@koppen I have no interest in overruling you here, but I see no harm in these changes. I'm mostly glad to see someone tending the garden.

**Comment by koppen** [comment]
Feel free to overrule me :) This isn't my project in any shape or form. Merging this is, however, going to cause tons of conflicts with https://github.com/copenhagenrb/copenhagenrb.github.io/pull/15, so bear that in mind.

**Comment by omegahm** [comment]
Merge #15 first, and I'll rebase this one afterwards :smirk:

**Comment by jamiehodge** [comment]
@omegahm done

**Comment by omegahm** [comment]
@jamiehodge So am I :smile:

**Pull request merged**
